import Link from "next/link";
import { ArrowLeft, Bell, BookOpenCheck, Mail, Plus, ShieldCheck } from "lucide-react";
import { PageHeading } from "@/components/portal/page-heading";
import { WorkspaceCard, SectionTitle } from "@/components/school/workspace-ui";
import { getManagedSchool } from "@/lib/schools/managed-school";
import { addAdmissionQuestion, deactivateAdmissionQuestion, saveAdmissionSettings, savePrivateAdmissionSettings, updateAdmissionClassAvailability, updateSchoolAdmissionsStatus } from "@/app/admissions/actions";

type Props = { searchParams?: Promise<Record<string, string | string[] | undefined>> };
const field = "mt-1.5 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm";

export default async function AdmissionsSettingsPage({ searchParams }: Props) {
  const { school, supabase, membership } = await getManagedSchool();
  if (!school) return <PageHeading title="Admissions setup" description="Set up a school profile before configuring admissions." />;
  const [{ data: settings }, { data: classes }, { data: questions }, { data: privateSettings }] = await Promise.all([
    supabase.from("school_admission_settings").select("*").eq("school_id", school.id).maybeSingle(),
    supabase.from("school_classes").select("id, name, branch_id, accepting_applications").eq("school_id", school.id).order("name"),
    supabase.from("school_application_questions").select("id, prompt, answer_type, options, is_required, is_active").eq("school_id", school.id).order("sort_order"),
    supabase.from("school_admission_private_settings").select("admissions_contact_person, internal_notification_email, notify_new_applications, notify_parent_replies").eq("school_id", school.id).maybeSingle(),
  ]);
  const params = searchParams ? await searchParams : {};
  const saved = Array.isArray(params.saved) ? params.saved[0] : params.saved;
  const error = Array.isArray(params.error) ? params.error[0] : params.error;
  const feedback: Record<string, string> = { status: "Admissions status updated.", settings: "Admissions period and preferences saved.", question: "School question saved.", class: "Class availability updated.", "private-contact": "Private admissions contact preferences saved." };
  const errors: Record<string, string> = { permission: "Your school role does not allow admissions administration.", status: "We couldn’t update admissions status.", details: "Check the intake year, dates and required fields.", question: "Check your question and select options.", options: "A select question needs at least two answer choices.", class: "We couldn’t change that class availability.", "private-contact": "Check the contact name and email address.", save: "We couldn’t save the admissions setup. Please try again." };
  const canConfigure = Boolean(membership && ["owner", "administrator", "admissions"].includes(membership.role));
  return <>
    <Link href="/school/admissions" className="inline-flex min-h-10 items-center gap-2 text-sm font-bold text-emerald-800 hover:underline"><ArrowLeft className="size-4" />Admissions overview</Link>
    <div className="mt-5"><PageHeading eyebrow={school.name} title="Admissions setup" description="Set the intake window, eligible classes, family-facing instructions and private team notifications." /></div>
    {saved && feedback[saved] && <p role="status" className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-950">{feedback[saved]}</p>}
    {error && errors[error] && <p role="alert" className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm font-bold text-amber-950">{errors[error]}</p>}
    {!canConfigure && <p role="alert" className="mt-5 rounded-xl bg-amber-50 p-4 text-sm text-amber-950">Only the school owner, administrator or admissions member can change this setup.</p>}

    <div className="mt-6 space-y-5">
      <WorkspaceCard><SectionTitle title="Intake status" description="This status is visible on the published school profile." /><form action={updateSchoolAdmissionsStatus} className="mt-4 flex flex-wrap items-end gap-3"><input type="hidden" name="schoolId" value={school.id} /><label className="min-w-52 flex-1 text-xs font-bold text-slate-700">Admissions status<select name="admissionStatus" defaultValue={String(school.admission_status)} className={field}><option value="open">Open</option><option value="opening_soon">Opening soon</option><option value="closed">Closed</option></select></label><button disabled={!canConfigure} className="min-h-11 rounded-xl bg-emerald-800 px-4 text-sm font-extrabold text-white disabled:opacity-50">Save status</button></form><p className="mt-3 text-xs leading-5 text-slate-500">The online Apply button appears only when the platform admissions flag, this school’s open intake, dates and an accepting class all agree.</p></WorkspaceCard>

      <WorkspaceCard><SectionTitle title="Application period & options" description="Opening and closing times are evaluated on the server when a parent applies." /><form action={saveAdmissionSettings} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="schoolId" value={school.id} /><label className="text-xs font-bold text-slate-700">Academic year<input name="academicYear" defaultValue={settings?.academic_year ?? ""} placeholder="2026/2027" pattern="[0-9]{4}/[0-9]{4}" className={field} /></label><label className="text-xs font-bold text-slate-700">Term/intake<input name="term" defaultValue={settings?.term ?? ""} placeholder="First term" maxLength={80} className={field} /></label><label className="text-xs font-bold text-slate-700">Applications open at<input name="opensAt" type="datetime-local" defaultValue={settings?.opens_at ? new Date(settings.opens_at).toISOString().slice(0, 16) : ""} className={field} /></label><label className="text-xs font-bold text-slate-700">Applications close at<input name="closesAt" type="datetime-local" defaultValue={settings?.closes_at ? new Date(settings.closes_at).toISOString().slice(0, 16) : ""} className={field} /></label><label className="text-xs font-bold text-slate-700 sm:col-span-2">Instructions for parents<textarea name="instructions" defaultValue={settings?.instructions ?? ""} rows={4} maxLength={4000} className={`${field} py-3`} placeholder="Tell parents about the admissions process and what to prepare." /></label><div className="grid gap-2 sm:col-span-2 sm:grid-cols-3"><label className="flex min-h-11 items-center gap-2 rounded-xl bg-slate-50 px-3 text-sm font-semibold"><input type="checkbox" name="applicationsEnabled" defaultChecked={settings?.applications_enabled ?? false} className="size-4 accent-emerald-800" />Accept applications through Skulena</label><label className="flex min-h-11 items-center gap-2 rounded-xl bg-slate-50 px-3 text-sm font-semibold"><input type="checkbox" name="visitsEnabled" defaultChecked={settings?.visits_enabled ?? true} className="size-4 accent-emerald-800" />Allow visit requests</label><label className="flex min-h-11 items-center gap-2 rounded-xl bg-slate-50 px-3 text-sm font-semibold"><input type="checkbox" name="assessmentsEnabled" defaultChecked={settings?.assessments_enabled ?? false} className="size-4 accent-emerald-800" />Allow assessments</label><label className="flex min-h-11 items-center gap-2 rounded-xl bg-slate-50 px-3 text-sm font-semibold"><input type="checkbox" name="interviewsEnabled" defaultChecked={settings?.interviews_enabled ?? false} className="size-4 accent-emerald-800" />Allow interviews</label></div><button disabled={!canConfigure} className="min-h-11 rounded-xl bg-emerald-800 px-4 text-sm font-extrabold text-white disabled:opacity-50 sm:col-span-2">Save intake setup</button></form></WorkspaceCard>

      <WorkspaceCard><SectionTitle title="Classes accepting applications" description="The parent application only offers a class your team marks as open." /><div className="mt-4 divide-y divide-slate-100">{classes?.length ? classes.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="font-bold text-slate-800">{item.name}</p><p className="text-xs text-slate-500">{item.branch_id ? "Branch-specific class" : "School class"}</p></div><form action={updateAdmissionClassAvailability}><input type="hidden" name="schoolId" value={school.id} /><input type="hidden" name="classId" value={item.id} /><input type="hidden" name="accepting" value={item.accepting_applications ? "false" : "true"} /><button disabled={!canConfigure} className={`min-h-10 rounded-lg px-3 text-xs font-bold disabled:opacity-50 ${item.accepting_applications ? "bg-emerald-50 text-emerald-900" : "bg-slate-100 text-slate-700"}`}>{item.accepting_applications ? "Accepting · turn off" : "Not accepting · turn on"}</button></form></div>) : <p className="py-3 text-sm text-slate-600">No classes have been added to this school yet. Add them in school profile setup first.</p>}</div></WorkspaceCard>

      <WorkspaceCard><SectionTitle title="Admissions checklist" description="These requirements are published on the school profile. Edit the list on the admissions overview." /><div className="mt-3"><Link href="/school/admissions#admission-details" className="text-sm font-bold text-emerald-800 underline">Edit published requirements and parent instructions</Link></div><p className="mt-2 text-xs text-slate-500">Use clear, proportionate requirements. Avoid collecting child medical or identity data unless it is genuinely necessary for this admissions process.</p></WorkspaceCard>

      <WorkspaceCard><SectionTitle title="School-specific application questions" description="Questions are presented to parents during the application and their answers stay linked to that application." /><div className="mt-3 space-y-2">{(questions ?? []).map((question) => <div key={question.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-slate-50 p-3"><div><p className="text-sm font-bold text-slate-800">{question.prompt}{question.is_required ? " · Required" : " · Optional"}</p><p className="mt-1 text-xs capitalize text-slate-500">{question.answer_type.replaceAll("_", " ")}{question.answer_type === "select" && Array.isArray(question.options) ? ` · ${question.options.join(", ")}` : ""}{!question.is_active ? " · Inactive" : ""}</p></div>{question.is_active && <form action={deactivateAdmissionQuestion}><input type="hidden" name="schoolId" value={school.id} /><input type="hidden" name="questionId" value={question.id} /><button disabled={!canConfigure} className="text-xs font-bold text-rose-700 underline disabled:opacity-50">Deactivate</button></form>}</div>)}{!questions?.length && <p className="text-sm text-slate-600">No extra school-specific questions.</p>}</div><form action={addAdmissionQuestion} className="mt-5 grid gap-3 rounded-xl border border-dashed border-slate-300 p-4 sm:grid-cols-2"><input type="hidden" name="schoolId" value={school.id} /><h3 className="flex items-center gap-2 font-extrabold text-[#0e2946] sm:col-span-2"><Plus className="size-4" />Add a question</h3><label className="text-xs font-bold text-slate-700 sm:col-span-2">Question<input name="prompt" required minLength={2} maxLength={500} className={field} /></label><label className="text-xs font-bold text-slate-700">Answer type<select name="answerType" className={field}><option value="short_text">Short answer</option><option value="long_text">Long answer</option><option value="yes_no">Yes / no</option><option value="select">Choose from options</option></select></label><label className="text-xs font-bold text-slate-700">Select choices (one per line)<textarea name="options" rows={3} maxLength={1500} className={`${field} py-2`} placeholder="Only used for choice questions" /></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="isRequired" className="size-4 accent-emerald-800" />Required to submit</label><button disabled={!canConfigure} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-lg bg-emerald-800 px-3 text-xs font-extrabold text-white disabled:opacity-50"><BookOpenCheck className="size-4" />Add question</button></form></WorkspaceCard>

      <WorkspaceCard><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-emerald-800" /><SectionTitle title="Private admissions contacts" description="Visible to authorized admissions team members only. These contacts are never shown on public school profiles." /></div><form action={savePrivateAdmissionSettings} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="schoolId" value={school.id} /><label className="text-xs font-bold text-slate-700">Admissions contact person<input name="admissionsContactPerson" defaultValue={privateSettings?.admissions_contact_person ?? ""} maxLength={160} className={field} /></label><label className="text-xs font-bold text-slate-700">Internal notification email<input name="internalNotificationEmail" type="email" defaultValue={privateSettings?.internal_notification_email ?? ""} maxLength={254} className={field} /></label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="notifyNewApplications" defaultChecked={privateSettings?.notify_new_applications ?? true} className="size-4 accent-emerald-800" /><Bell className="size-4" />In-app alert for new applications</label><label className="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="notifyParentReplies" defaultChecked={privateSettings?.notify_parent_replies ?? true} className="size-4 accent-emerald-800" /><Mail className="size-4" />In-app alert for parent replies</label><p className="rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-950 sm:col-span-2">Email delivery is not configured. These preferences do not send email; in-app notifications are the only active channel.</p><button disabled={!canConfigure} className="min-h-11 rounded-xl bg-emerald-800 px-4 text-sm font-extrabold text-white disabled:opacity-50 sm:col-span-2">Save private preferences</button></form></WorkspaceCard>
    </div>
  </>;
}
