import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, CalendarDays, Check, CircleDollarSign, FileText, MessageSquareText, School } from "lucide-react";
import { PageHeading } from "@/components/portal/page-heading";
import { createClient } from "@/lib/supabase/server";
import { requireAccount } from "@/lib/auth";
import { acceptVisitReschedule, cancelSchoolVisit, decideAdmissionOffer, requestSchoolVisit, sendAdmissionMessage, submitDraftApplication } from "@/app/admissions/actions";
import { AdmissionDocumentUploader } from "@/components/parent/admission-document-uploader";

type Props = { params: Promise<{ id: string }>; searchParams?: Promise<Record<string, string | string[] | undefined>> };
const statusLabel: Record<string, string> = { draft: "Draft", submitted: "Submitted", received: "Received", under_review: "Under review", information_required: "Information required", visit_required: "Visit requested", visit_scheduled: "Visit scheduled", assessment_required: "Assessment required", assessment_scheduled: "Assessment scheduled", interview_required: "Interview required", interview_scheduled: "Interview scheduled", decision_pending: "Decision pending", offered: "Offer received", accepted: "Offer accepted", declined: "Declined", withdrawn: "Withdrawn", cancelled: "Cancelled", enrolled: "Enrolled" };
const kobo = (value: number | string) => {
  const digits = String(value).replace(/\D/g, "");
  if (!digits) return "Amount unavailable";
  const padded = digits.padStart(3, "0");
  const naira = padded.slice(0, -2).replace(/\B(?=(\d{3})+(?!\d))/g, ",");
  return `₦${naira}.${padded.slice(-2)}`;
};
const dateTime = (value: string | null) => value ? new Date(value).toLocaleString("en-NG", { dateStyle: "medium", timeStyle: "short" }) : "Not scheduled";

export default async function ParentApplicationDetail({ params, searchParams }: Props) {
  const { id } = await params;
  const [{ user }, supabase] = await Promise.all([requireAccount(["parent"]), createClient()]);
  if (!supabase) notFound();
  const { data: application } = await supabase.from("admission_applications").select("*").eq("id", id).eq("parent_id", user.id).maybeSingle();
  if (!application) notFound();
  const [schoolResult, childResult, answersResult, historyResult, activityResult, docsResult, visitsResult, assessmentsResult, messagesResult, offersResult, invoicesResult] = await Promise.all([
    supabase.from("public_school_profiles").select("id, slug, name").eq("id", application.school_id).maybeSingle(),
    supabase.from("children").select("id, first_name, last_name").eq("id", application.child_id).maybeSingle(),
    supabase.from("admission_application_answers").select("id, question_snapshot, answer").eq("application_id", id).order("created_at"),
    supabase.from("admission_application_status_history").select("id, previous_status, new_status, created_at").eq("application_id", id).order("created_at", { ascending: false }),
    supabase.from("admission_activity").select("id, event_key, safe_metadata, created_at").eq("application_id", id).eq("parent_visible", true).order("created_at", { ascending: false }),
    supabase.from("admission_documents").select("id, category, file_name, storage_path, mime_type, byte_size, created_at").eq("application_id", id).order("created_at", { ascending: false }),
    supabase.from("school_visits").select("id, status, scheduled_at, proposed_at, instructions, created_at").eq("application_id", id).order("created_at", { ascending: false }),
    supabase.from("school_assessments").select("id, assessment_type, status, scheduled_at, location, instructions").eq("application_id", id).eq("parent_visible", true).order("scheduled_at"),
    supabase.from("admission_messages").select("id, sender_id, body, created_at").eq("application_id", id).order("created_at"),
    supabase.from("admission_offers").select("id, offer_version, status, issued_at, expires_at, conditions, required_documents, next_steps, decision_at").eq("application_id", id).order("offer_version", { ascending: false }),
    supabase.from("school_invoices").select("id, invoice_number, academic_year, term, total_minor, due_date, status, issued_at").eq("application_id", id).order("created_at", { ascending: false }),
  ]);
  const invoices = invoicesResult.data ?? [];
  const { data: invoiceItems } = invoices.length ? await supabase.from("school_invoice_items").select("invoice_id, category, description, quantity, unit_amount_minor, line_total_minor").in("invoice_id", invoices.map((invoice) => invoice.id)) : { data: [] };
  const paramsValue = searchParams ? await searchParams : {};
  const saved = Array.isArray(paramsValue.saved) ? paramsValue.saved[0] : paramsValue.saved;
  const schoolName = schoolResult.data?.name ?? "School";
  const childName = childResult.data ? `${childResult.data.first_name} ${childResult.data.last_name}` : "Child profile";
  const finalStatuses = ["declined", "withdrawn", "cancelled", "enrolled"];

  return <>
    <Link href="/parent/applications" className="inline-flex min-h-10 items-center gap-2 text-sm font-bold text-emerald-800 hover:underline"><ArrowLeft className="size-4" />All applications</Link>
    {saved && <p role="status" className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-bold text-emerald-950">Your update was saved.</p>}
    <div className="mt-5"><PageHeading eyebrow={application.application_number} title={schoolName} description={`${childName} · ${application.class_name} · ${application.academic_year} · ${application.term}`} action={<span className="rounded-full bg-emerald-50 px-3 py-2 text-xs font-extrabold text-emerald-900">{statusLabel[application.status] ?? application.status}</span>} /></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[minmax(0,1fr)_340px]">
      <div className="space-y-5">
        <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-extrabold text-[#0e2946]">Application progress</h2><ol className="mt-4 space-y-3">{(historyResult.data ?? []).map((event) => <li key={event.id} className="flex gap-3"><span className="mt-1 grid size-6 shrink-0 place-items-center rounded-full bg-emerald-50 text-emerald-800"><Check className="size-3.5" /></span><div><p className="text-sm font-bold text-slate-800">{event.previous_status ? `${statusLabel[event.previous_status] ?? event.previous_status} → ` : "Application created · "}{statusLabel[event.new_status] ?? event.new_status}</p><time className="mt-1 block text-xs text-slate-500">{dateTime(event.created_at)}</time></div></li>)}</ol></section>

        {(answersResult.data ?? []).length > 0 && <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-extrabold text-[#0e2946]">Your answers</h2><dl className="mt-4 space-y-4">{(answersResult.data ?? []).map((answer) => <div key={answer.id}><dt className="text-xs font-bold text-slate-500">{answer.question_snapshot}</dt><dd className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-800">{answer.answer}</dd></div>)}</dl></section>}

        {(activityResult.data ?? []).length > 0 && <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><h2 className="text-lg font-extrabold text-[#0e2946]">Recent activity</h2><ol className="mt-3 space-y-3">{(activityResult.data ?? []).map((event) => <li key={event.id} className="flex justify-between gap-4 border-b border-slate-100 pb-3 text-sm"><span className="font-semibold capitalize text-slate-700">{event.event_key.replaceAll("_", " ")}</span><time className="shrink-0 text-xs text-slate-500">{dateTime(event.created_at)}</time></li>)}</ol></section>}

        <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><FileText className="size-5 text-emerald-800" /><h2 className="text-lg font-extrabold text-[#0e2946]">Admission documents</h2></div>
          {(docsResult.data ?? []).length ? <ul className="mt-4 divide-y divide-slate-100">{(docsResult.data ?? []).map((doc) => <li key={doc.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><p className="text-sm font-bold text-slate-800">{doc.file_name}</p><p className="mt-1 text-xs capitalize text-slate-500">{doc.category.replaceAll("_", " ")} · {(doc.byte_size / 1024 / 1024).toFixed(1)} MB</p></div><a href={`/api/admission-documents/${doc.id}`} className="text-sm font-bold text-emerald-800 underline">Open securely</a></li>)}</ul> : <p className="mt-3 text-sm text-slate-600">No admission documents uploaded.</p>}
          {!["draft", "information_required"].includes(application.status) ? <p className="mt-4 text-xs text-slate-500">Documents are locked after submission unless the school requests more information.</p> : <div className="mt-5"><AdmissionDocumentUploader applicationId={id} initialDocuments={docsResult.data ?? []} showExistingDocuments={false} /></div>}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><MessageSquareText className="size-5 text-emerald-800" /><h2 className="text-lg font-extrabold text-[#0e2946]">Messages with the school</h2></div>
          <div className="mt-4 space-y-3">{(messagesResult.data ?? []).map((message) => <article key={message.id} className={`max-w-[90%] rounded-2xl p-3 ${message.sender_id === user.id ? "ml-auto bg-emerald-50" : "bg-slate-100"}`}><p className="text-[10px] font-extrabold uppercase tracking-wide text-slate-500">{message.sender_id === user.id ? "You" : "School admissions"}</p><p className="mt-1 whitespace-pre-wrap text-sm leading-6 text-slate-800">{message.body}</p><time className="mt-2 block text-[10px] text-slate-500">{dateTime(message.created_at)}</time></article>)}{!messagesResult.data?.length && <p className="text-sm text-slate-600">No messages yet.</p>}</div>
          {!finalStatuses.includes(application.status) && <form action={sendAdmissionMessage} className="mt-4"><input type="hidden" name="applicationId" value={id} /><label className="block text-xs font-bold text-slate-700">Send a message<textarea name="body" required minLength={1} maxLength={4000} rows={3} className="mt-1.5 w-full rounded-xl border border-slate-300 p-3 text-sm" placeholder="Ask a question or reply to the school…" /></label><button className="mt-2 min-h-10 rounded-lg bg-emerald-800 px-4 text-sm font-extrabold text-white">Send message</button></form>}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><CalendarDays className="size-5 text-emerald-800" /><h2 className="text-lg font-extrabold text-[#0e2946]">Visits and assessments</h2></div>
          <div className="mt-4 space-y-3">{(visitsResult.data ?? []).map((visit) => <article key={visit.id} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-bold capitalize text-slate-800">School visit · {visit.status.replaceAll("_", " ")}</p><p className="text-xs text-slate-600">{dateTime(visit.scheduled_at ?? visit.proposed_at)}</p></div>{visit.instructions && <p className="mt-2 text-sm leading-5 text-slate-600">{visit.instructions}</p>}{visit.status === "reschedule_proposed" && <form action={acceptVisitReschedule} className="mt-3"><input type="hidden" name="applicationId" value={id} /><input type="hidden" name="visitId" value={visit.id} /><button className="min-h-9 rounded-lg bg-emerald-800 px-3 text-xs font-extrabold text-white">Accept proposed time</button></form>}{["requested", "confirmed", "reschedule_proposed"].includes(visit.status) && <form action={cancelSchoolVisit} className="mt-3"><input type="hidden" name="applicationId" value={id} /><input type="hidden" name="visitId" value={visit.id} /><button className="text-xs font-bold text-rose-700 underline">Cancel visit request</button></form>}</article>)}
            {(assessmentsResult.data ?? []).map((assessment) => <article key={assessment.id} className="rounded-xl bg-indigo-50 p-4"><div className="flex flex-wrap justify-between gap-2"><p className="text-sm font-bold capitalize text-indigo-950">{assessment.assessment_type} · {assessment.status}</p><p className="text-xs text-indigo-800">{dateTime(assessment.scheduled_at)}</p></div>{assessment.location && <p className="mt-2 text-xs text-indigo-900">{assessment.location}</p>}{assessment.instructions && <p className="mt-1 text-sm leading-5 text-indigo-900">{assessment.instructions}</p>}</article>)}
            {!visitsResult.data?.length && !assessmentsResult.data?.length && <p className="text-sm text-slate-600">No visit or assessment is scheduled.</p>}</div>
          {!finalStatuses.includes(application.status) && !(visitsResult.data ?? []).some((visit) => ["requested", "confirmed", "reschedule_proposed"].includes(visit.status)) && <form action={requestSchoolVisit} className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><input type="hidden" name="applicationId" value={id} /><label className="block text-xs font-bold text-emerald-950">Request a school visit (optional)<textarea name="parentNote" maxLength={1000} rows={2} className="mt-1.5 w-full rounded-lg border border-emerald-200 bg-white p-3 text-sm" placeholder="Any timing or accessibility details for the school?" /></label><button className="mt-2 min-h-9 rounded-lg bg-emerald-800 px-3 text-xs font-extrabold text-white">Request visit</button></form>}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><School className="size-5 text-emerald-800" /><h2 className="text-lg font-extrabold text-[#0e2946]">Admission decision</h2></div>
          {(offersResult.data ?? []).length ? <div className="mt-4 space-y-3">{(offersResult.data ?? []).map((offer) => <article key={offer.id} className="rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-extrabold text-emerald-950">Admission offer · version {offer.offer_version}</h3><span className="rounded-full bg-white px-2 py-1 text-xs font-bold capitalize text-emerald-900">{offer.status}</span></div><p className="mt-2 text-xs text-emerald-900">Issued {dateTime(offer.issued_at)}{offer.expires_at ? ` · Expires ${dateTime(offer.expires_at)}` : ""}</p>{offer.conditions && <p className="mt-3 whitespace-pre-line text-sm leading-6 text-slate-800">{offer.conditions}</p>}{offer.required_documents?.length > 0 && <div className="mt-3 text-sm text-slate-700"><strong>Required documents:</strong><ul className="mt-1 list-disc pl-5">{offer.required_documents.map((doc: string) => <li key={doc}>{doc}</li>)}</ul></div>}{offer.next_steps && <p className="mt-3 text-sm text-slate-700">Next steps: {offer.next_steps}</p>}{offer.status === "issued" && <div className="mt-4 flex flex-wrap gap-2"><form action={decideAdmissionOffer}><input type="hidden" name="applicationId" value={id} /><input type="hidden" name="offerId" value={offer.id} /><input type="hidden" name="decision" value="accepted" /><button className="min-h-10 rounded-lg bg-emerald-800 px-4 text-sm font-extrabold text-white">Accept offer</button></form><form action={decideAdmissionOffer}><input type="hidden" name="applicationId" value={id} /><input type="hidden" name="offerId" value={offer.id} /><input type="hidden" name="decision" value="declined" /><button className="min-h-10 rounded-lg border border-rose-300 px-4 text-sm font-bold text-rose-800">Decline</button></form></div>}</article>)}</div> : <p className="mt-3 text-sm text-slate-600">No admission offer has been issued.</p>}
        </section>

        <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><CircleDollarSign className="size-5 text-emerald-800" /><h2 className="text-lg font-extrabold text-[#0e2946]">School invoice</h2></div>
          {invoices.length ? <div className="mt-4 space-y-3">{invoices.map((invoice) => <article key={invoice.id} className="rounded-xl bg-slate-50 p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-extrabold text-[#0e2946]">{invoice.invoice_number}</p><span className="text-xs font-bold capitalize text-slate-600">{invoice.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-xs text-slate-500">{invoice.academic_year} · {invoice.term}{invoice.due_date ? ` · Due ${new Date(`${invoice.due_date}T00:00:00`).toLocaleDateString("en-NG", { dateStyle: "medium" })}` : ""}</p><ul className="mt-3 divide-y divide-slate-200">{(invoiceItems ?? []).filter((item) => item.invoice_id === invoice.id).map((item) => <li key={`${item.invoice_id}-${item.description}`} className="flex justify-between gap-3 py-2 text-xs"><span>{item.description} × {item.quantity}</span><span className="font-bold">{kobo(item.line_total_minor)}</span></li>)}</ul><div className="mt-3 border-t border-slate-200 pt-3 text-right text-sm font-extrabold text-[#0e2946]">Total {kobo(invoice.total_minor)}</div><p className="mt-2 text-[11px] leading-5 text-slate-500">Pay the school directly using its verified instructions. Skulena has not collected a payment.</p></article>)}</div> : <p className="mt-3 text-sm text-slate-600">No school invoice has been issued.</p>}
          <p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs leading-5 text-amber-950">SchoolPay financing and online payment are not configured. This application does not represent a financing decision or proof of payment.</p>
        </section>
      </div>

      <aside className="space-y-4"><section className="rounded-2xl border border-slate-200 bg-white p-5"><h2 className="font-extrabold text-[#0e2946]">Application details</h2><dl className="mt-3 space-y-3 text-sm"><div><dt className="text-xs text-slate-500">Reference</dt><dd className="font-bold">{application.application_number}</dd></div><div><dt className="text-xs text-slate-500">Class</dt><dd className="font-bold">{application.class_name}</dd></div><div><dt className="text-xs text-slate-500">Guardian</dt><dd className="font-bold">{application.guardian_name}</dd></div><div><dt className="text-xs text-slate-500">Payment preference</dt><dd className="font-bold">Pay school directly</dd></div><div><dt className="text-xs text-slate-500">Created</dt><dd className="font-bold">{dateTime(application.created_at)}</dd></div></dl></section>
        {application.status === "draft" && <form action={submitDraftApplication} className="rounded-2xl border border-emerald-200 bg-white p-5"><input type="hidden" name="applicationId" value={id} /><label className="flex items-start gap-2 text-xs leading-5 text-slate-700"><input type="checkbox" name="consentAccepted" required className="mt-1 size-4 accent-emerald-800" />I confirm the application information is accurate and agree to share it with the school.</label><button className="mt-4 min-h-10 w-full rounded-lg bg-emerald-800 px-4 text-sm font-extrabold text-white">Submit saved application</button></form>}
        {schoolResult.data?.slug && <Link href={`/school/${encodeURIComponent(schoolResult.data.slug)}/admissions`} className="block rounded-xl border border-slate-200 bg-white p-4 text-sm font-bold text-emerald-800 hover:border-emerald-300">School admissions information →</Link>}
      </aside>
    </div>
  </>;
}
