"use client";
import { useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { ImagePlus, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { createClient } from "@/lib/supabase/client";
import { registerMediaRecord } from "@/app/school/(portal)/media/actions";

const mimeTypes = ["image/jpeg", "image/png", "image/webp", "video/mp4", "video/webm"] as const;
export function MediaUploader({ schoolId }: { schoolId: string }) {
  const router = useRouter(); const inputRef = useRef<HTMLInputElement>(null); const [category, setCategory] = useState("Campus"); const [caption, setCaption] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function upload() { const file = inputRef.current?.files?.[0]; if (!file) { setMessage("Choose an image or video first."); return; } if (!mimeTypes.includes(file.type as typeof mimeTypes[number])) { setMessage("Use JPEG, PNG, WebP, MP4 or WebM."); return; } const mediaType = file.type.startsWith("image/") ? "image" : "video"; const max = mediaType === "image" ? 10485760 : 104857600; if (file.size > max) { setMessage(mediaType === "image" ? "Images must be 10 MB or smaller." : "Videos must be 100 MB or smaller."); return; }
    setBusy(true); setMessage(""); const supabase = createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setBusy(false); setMessage("Sign in again before uploading."); return; }
    const extension = { "image/jpeg": "jpg", "image/png": "png", "image/webp": "webp", "video/mp4": "mp4", "video/webm": "webm" }[file.type]; const storagePath = `${schoolId}/${user.id}/${crypto.randomUUID()}.${extension}`;
    const { error: uploadError } = await supabase.storage.from("school-media").upload(storagePath, file, { contentType: file.type, upsert: false }); if (uploadError) { setBusy(false); setMessage("Upload failed. Please try again."); return; }
    const result = await registerMediaRecord({ schoolId, category, caption, mediaType, storagePath, mimeType: file.type, byteSize: file.size }); if (result.error) { await supabase.storage.from("school-media").remove([storagePath]); setMessage(result.error); } else { setMessage("Uploaded for moderation."); setCaption(""); if (inputRef.current) inputRef.current.value = ""; router.refresh(); } setBusy(false);
  }
  return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><div className="flex items-center gap-3"><ImagePlus className="size-5 text-emerald-700" /><h2 className="font-extrabold text-[#0e2946]">Upload school media</h2></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Category<select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-2 h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option>Campus</option><option>Classrooms</option><option>Science Laboratory</option><option>ICT Laboratory</option><option>Library</option><option>Sports</option><option>Playground</option><option>Transportation</option><option>Dining</option><option>Kitchen</option><option>Sick Bay</option><option>Toilets</option><option>Boarding</option><option>Security</option></select></label><label className="text-sm font-bold text-slate-700">File<input ref={inputRef} type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" className="mt-2 block w-full text-sm" /></label></div><label className="mt-4 block text-sm font-bold text-slate-700">Caption<input value={caption} onChange={(event) => setCaption(event.target.value)} maxLength={300} className="mt-2 h-11 w-full rounded-xl border border-slate-300 bg-white px-3" /></label>{message && <p role="status" className="mt-3 text-sm font-semibold text-slate-600">{message}</p>}<Button type="button" className="mt-4" onClick={upload} disabled={busy}>{busy ? <LoaderCircle className="size-4 animate-spin" /> : <ImagePlus className="size-4" />}{busy ? "Uploading…" : "Upload for review"}</Button></div>;
}
