"use client";

import { useState } from "react";
import Link from "next/link";
import { useForm, useWatch } from "react-hook-form";
import { ArrowLeft, ArrowRight, Check, Cloud, LoaderCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { onboardingSchema, type OnboardingValues } from "@/lib/validation/school";
import { saveOnboardingStep, submitSchool } from "@/app/for-schools/register/actions";
import { MediaUploader } from "@/components/school/media-uploader";

const steps = ["Basic information", "Location", "Levels", "Structure", "Curriculum", "Facilities", "Fees", "Photos & videos", "Admissions", "Review"];
const levelOptions = [["creche", "Creche"], ["nursery", "Nursery"], ["primary", "Primary"], ["junior_secondary", "Junior Secondary"], ["senior_secondary", "Senior Secondary"]] as const;
const curriculumOptions = [["nigerian", "Nigerian"], ["british", "British"], ["american", "American"], ["montessori", "Montessori"], ["cambridge", "Cambridge"], ["ib", "IB"], ["other", "Other"]] as const;
const facilityOptions = [["classrooms", "Classrooms"], ["science_laboratory", "Science Laboratory"], ["ict_laboratory", "ICT Laboratory"], ["library", "Library"], ["playground", "Playground"], ["sports", "Sports Facilities"], ["school_bus", "School Bus"], ["dining", "Dining"], ["kitchen", "Kitchen"], ["sick_bay", "Sick Bay"], ["toilets", "Toilets"], ["boarding", "Boarding"], ["security", "Security"], ["special_needs", "Special Needs Facilities"], ["other", "Other"]] as const;
const input = "mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-4 text-[#0e2946] focus:border-emerald-600 focus:outline-none focus:ring-4 focus:ring-emerald-600/10";
const textarea = "mt-2 w-full rounded-xl border border-slate-300 bg-white p-4 text-[#0e2946] focus:border-emerald-600 focus:outline-none focus:ring-4 focus:ring-emerald-600/10";

function CheckGrid({ name, options, register }: { name: "levels" | "curricula" | "facilities"; options: readonly (readonly [string, string])[]; register: ReturnType<typeof useForm<OnboardingValues>>["register"] }) {
  return <div className="grid gap-3 sm:grid-cols-2">{options.map(([value, label]) => <label key={value} className="flex min-h-13 cursor-pointer items-center gap-3 rounded-xl border border-slate-200 p-4 has-[:checked]:border-emerald-600 has-[:checked]:bg-emerald-50"><input type="checkbox" value={value} {...register(name)} className="size-4 accent-emerald-700" /><span className="text-sm font-bold text-slate-700">{label}</span></label>)}</div>;
}

export function OnboardingForm({ initialValues, initialCompletion }: { initialValues: OnboardingValues; initialCompletion: number }) {
  const [step, setStep] = useState(initialValues.step || 1); const [schoolId, setSchoolId] = useState(initialValues.schoolId); const [completion, setCompletion] = useState(initialCompletion); const [status, setStatus] = useState<"idle" | "saving" | "saved" | "error" | "submitted">("idle"); const [message, setMessage] = useState(""); const [pendingMediaCount, setPendingMediaCount] = useState(0);
  const { control, register, getValues, setValue, formState: { errors } } = useForm<OnboardingValues>({ defaultValues: initialValues });
  const watchedValues = useWatch({ control });
  const hasUnuploadedMedia = step === 8 && pendingMediaCount > 0;
  const values: OnboardingValues = {
    ...initialValues,
    ...watchedValues,
    levels: watchedValues.levels ?? [],
    curricula: watchedValues.curricula ?? [],
    facilities: watchedValues.facilities ?? [],
    admissionStatus: watchedValues.admissionStatus ?? "closed",
  };
  async function saveCurrent(next = true) {
    setStatus("saving"); setMessage("");
    const parsed = onboardingSchema.safeParse({ ...getValues(), schoolId, step });
    if (!parsed.success) { setStatus("error"); setMessage(parsed.error.issues[0]?.message ?? "Check this step."); return; }
    const result = await saveOnboardingStep(parsed.data);
    if (result.schoolId) { setSchoolId(result.schoolId); setValue("schoolId", result.schoolId); }
    if (result.error) { setStatus("error"); setMessage(result.error); return; }
    setCompletion(result.completion ?? completion); setStatus("saved"); if (next) setStep((current) => Math.min(10, current + 1));
  }
  async function submit() {
    if (!schoolId) { setMessage("Save the first step before submitting."); return; }
    setStatus("saving"); const result = await submitSchool(schoolId); if (result.error) { setStatus("error"); setMessage(result.error); } else setStatus("submitted");
  }
  if (status === "submitted") return <div className="rounded-3xl border border-emerald-200 bg-white p-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-full bg-emerald-100 text-emerald-700"><Check className="size-7" /></span><h1 className="mt-5 text-3xl font-extrabold text-[#0e2946]">Profile submitted</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-slate-600">Your school is now under review. Submission does not publish the profile or award a verification badge.</p><Button asChild className="mt-6"><Link href="/school/dashboard">Go to dashboard</Link></Button></div>;
  return <div className="grid gap-8 lg:grid-cols-[240px_minmax(0,1fr)]"><aside><div className="rounded-2xl border border-slate-200 bg-white p-5 lg:sticky lg:top-6"><p className="text-xs font-extrabold uppercase tracking-widest text-emerald-700">Profile completion</p><p className="mt-2 text-3xl font-extrabold text-[#0e2946]">{completion}%</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full bg-emerald-600 transition-all" style={{ width: `${completion}%` }} /></div><ol className="mt-5 hidden space-y-1 lg:block">{steps.map((label, index) => <li key={label}><button type="button" disabled={hasUnuploadedMedia && index + 1 !== step} onClick={() => setStep(index + 1)} className={`w-full rounded-lg px-3 py-2 text-left text-xs font-bold disabled:cursor-not-allowed disabled:opacity-50 ${step === index + 1 ? "bg-emerald-50 text-emerald-800" : "text-slate-500 hover:bg-slate-50"}`}>{index + 1}. {label}</button></li>)}</ol></div></aside>
    <section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-[0_24px_60px_-45px_rgba(14,41,70,.45)] sm:p-8"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-widest text-emerald-700">Step {step} of 10</p><h1 className="mt-2 text-2xl font-extrabold tracking-tight text-[#0e2946]">{steps[step - 1]}</h1></div><p aria-live="polite" className="flex items-center gap-2 text-xs font-bold text-slate-500">{status === "saving" ? <><LoaderCircle className="size-4 animate-spin" />Saving…</> : status === "saved" ? <><Cloud className="size-4 text-emerald-700" />Progress saved</> : "Saved as a draft"}</p></div>
      <div className="mt-7 space-y-5">
        {step === 1 && <><label className="block text-sm font-bold">School name<input {...register("name")} className={input} onBlur={(event) => { if (!values.slug) setValue("slug", event.target.value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")); }} /></label><label className="block text-sm font-bold">Profile address<input {...register("slug")} className={input} placeholder="greenfield-school" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">School type<select {...register("schoolType")} className={input}><option value="private">Private</option><option value="public">Public</option><option value="faith_based">Faith-based</option><option value="international">International</option><option value="other">Other</option></select></label><label className="block text-sm font-bold">Year established<input type="number" {...register("yearEstablished")} className={input} /></label></div><label className="block text-sm font-bold">Description<textarea {...register("description")} className={textarea} rows={5} /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">Contact email<input type="email" {...register("contactEmail")} className={input} /></label><label className="block text-sm font-bold">Phone<input {...register("contactPhone")} className={input} /></label></div><label className="block text-sm font-bold">Website<input type="url" {...register("websiteUrl")} className={input} placeholder="https://" /></label></>}
        {step === 2 && <><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">Country<input {...register("country")} className={input} /></label><label className="block text-sm font-bold">State<input {...register("state")} className={input} /></label><label className="block text-sm font-bold">City / LGA<input {...register("city")} className={input} /></label><label className="block text-sm font-bold">Area<input {...register("area")} className={input} /></label></div><label className="block text-sm font-bold">Full address<textarea {...register("addressLine")} className={textarea} rows={3} /></label><details className="rounded-xl bg-slate-50 p-4"><summary className="text-sm font-bold">Map coordinates (optional)</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Latitude<input {...register("latitude")} className={input} /></label><label className="text-sm font-bold">Longitude<input {...register("longitude")} className={input} /></label></div></details></>}
        {step === 3 && <fieldset><legend className="mb-4 text-sm leading-6 text-slate-600">Select every level currently offered.</legend><CheckGrid name="levels" options={levelOptions} register={register} /></fieldset>}
        {step === 4 && <div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">School structure<select {...register("structure")} className={input}><option value="day">Day</option><option value="boarding">Boarding</option><option value="day_and_boarding">Day & boarding</option></select></label><label className="block text-sm font-bold">Gender<select {...register("gender")} className={input}><option value="mixed">Mixed</option><option value="boys">Boys</option><option value="girls">Girls</option></select></label></div>}
        {step === 5 && <fieldset><legend className="mb-4 text-sm leading-6 text-slate-600">Select all curricula used at the school.</legend><CheckGrid name="curricula" options={curriculumOptions} register={register} /></fieldset>}
        {step === 6 && <fieldset><legend className="mb-4 text-sm leading-6 text-slate-600">Select the facilities available now.</legend><CheckGrid name="facilities" options={facilityOptions} register={register} /></fieldset>}
        {step === 7 && <><p className="text-sm leading-6 text-slate-600">Fees are optional. Add one starting line now; the fee manager supports more later.</p><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">Category<select {...register("feeCategory")} className={input}><option value="tuition">Tuition</option><option value="registration">Registration</option><option value="books">Books</option><option value="uniform">Uniform</option><option value="transport">Transport</option><option value="boarding">Boarding</option><option value="other">Other</option></select></label><label className="block text-sm font-bold">Amount (NGN)<input type="number" {...register("feeAmount")} className={input} /></label><label className="block text-sm font-bold">Term<input {...register("feeTerm")} className={input} placeholder="First term" /></label><label className="block text-sm font-bold">Academic year<input {...register("academicYear")} className={input} placeholder="2026/2027" /></label></div></>}
        {step === 8 && <>{schoolId ? <MediaUploader schoolId={schoolId} onPendingCountChange={setPendingMediaCount} /> : <p className="rounded-xl bg-amber-50 p-4 text-sm text-amber-950">Save the first step before uploading media.</p>}<p className="text-xs leading-5 text-slate-500">Upload and review each image or video here before continuing. New media appears publicly after moderation.</p></>}
        {step === 9 && <><label className="block text-sm font-bold">Admission status<select {...register("admissionStatus")} className={input}><option value="open">Open</option><option value="closed">Closed</option><option value="opening_soon">Opening soon</option></select></label><label className="block text-sm font-bold">Admission description<textarea {...register("admissionDescription")} className={textarea} rows={4} /></label><label className="block text-sm font-bold">Application requirements <span className="font-medium text-slate-500">(one per line)</span><textarea {...register("requirements")} className={textarea} rows={5} /></label></>}
        {step === 10 && <div className="space-y-4"><p className="rounded-xl bg-sky-50 p-4 text-sm leading-6 text-sky-950">Review your information before submitting. You can select any step from the progress list to make changes.</p>{[["School", values.name], ["Location", [values.area, values.city, values.state].filter(Boolean).join(", ")], ["Levels", values.levels.join(", ") || "Not added"], ["Curriculum", values.curricula.join(", ") || "Not added"], ["Facilities", `${values.facilities.length} selected`], ["Admissions", values.admissionStatus.replaceAll("_", " ")]].map(([label, value]) => <div key={label} className="border-b border-slate-100 pb-3"><p className="text-xs font-bold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm font-bold text-[#0e2946]">{value}</p></div>)}</div>}
      </div>
      {(message || Object.keys(errors).length > 0) && <p role="alert" className="mt-5 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-800">{message || "Check the highlighted information."}</p>}
      {hasUnuploadedMedia && <p role="status" className="mt-5 rounded-xl bg-amber-50 p-3 text-sm font-semibold text-amber-950">Upload or remove your {pendingMediaCount} selected {pendingMediaCount === 1 ? "file" : "files"} before moving to another step.</p>}
      <div className="mt-8 flex items-center justify-between gap-3"><Button type="button" variant="outline" disabled={step === 1 || status === "saving" || hasUnuploadedMedia} onClick={() => setStep((current) => Math.max(1, current - 1))}><ArrowLeft className="size-4" />Back</Button>{step < 10 ? <Button type="button" onClick={() => saveCurrent(true)} disabled={status === "saving" || hasUnuploadedMedia}>{status === "saving" ? "Saving…" : "Save & continue"}<ArrowRight className="size-4" /></Button> : <Button type="button" onClick={submit} disabled={status === "saving"}>Submit school</Button>}</div>
    </section></div>;
}
